language: node_js
node_js:
  - "4"
  - "5"
  - "stable"
sudo: false
script: "gulp coverage"
addons:
  code_climate:
    repo_token: 22418eb911d3c768016fd4ecb1803b2b26640d7b8b6451705f9ed4d82168c9f7
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info